### ISSUE TITLE
Won't run on arm64 raspberry pi

### ISSUE THREAD

**Issue by oregonpillow** [linuxserver/docker-papermerge#12]
Pulled successfully using `docker-compose up -d`, go to http://192.168.0.84:8000   and nothing loads. All my other docker containers on system work fine and are configured in similar manner which suggests that my network issues are not the problem but something wrong with the image.

Any suggestions?

**Comment by j0nnymoe** [comment]
It will be related to this: https://github.com/linuxserver/docker-papermerge/issues/4#issuecomment-695779275
