### ISSUE TITLE
Give option to link import folder with compose setup

### ISSUE THREAD

**Issue by metsnap** [linuxserver/docker-papermerge#13]
## Idea
It would be great to have an easy way to mount the import folder.

see: https://papermerge.readthedocs.io/en/latest/settings.html#importer-dir

**Comment by tapnl** [comment]
Really would appreciate this function as well.

**Comment by tapnl** [comment]
I looked a little bit further - the option is there!
Just add the following to the papermerge.conf.py file in the config folder

IMPORTER_DIR = “/data/import”

The above makes the folder import the worker folder. You do need to create this by yourself.
