### ISSUE TITLE
"New Group" does not create a new group

### ISSUE THREAD

**Issue by Goliath67** [linuxserver/docker-papermerge#14]
**Expected Behavior**
"New Group", put text then "Save" should create a group

**Current Behavior**
It doesn't.
I am unable to create a Group.
After clicking on Save, the page still says "No groups defined so far"

**Steps to Reproduce**
1. Click on "New Group"
2. Type in name of group
3. Click on "Save"

**Environment**

OS: CPU architecture: x86_64
Linux 4.4.59+ #25426 SMP PREEMPT Wed Jul 8 03:21:29 CST 2020 x86_64 GNU/Linux synology_apollolake_218+ 
DSM 6.2.3-25426 Update 2
Papermerge V1.5.0 docker image on Synology NAS

How docker service was installed:
Docker GUI application on Synology NAS

**Comment by j0nnymoe** [comment]
Please fill our the requested information that was in the issue template so we can help accordingly.

**Comment by Goliath67** [comment]
I have edited the original post to do so.

**Comment by j0nnymoe** [comment]
@Goliath67 excellent thank you - could you also attach some screenshots of the container info from DSM please? just showing the volume mounts/env values etc? 

I'll then test on my setup.

**Comment by Goliath67** [comment]
![image](https://user-images.githubusercontent.com/64475279/96993669-e8e48700-152b-11eb-88de-7a65a137526e.png)

**Comment by Goliath67** [comment]
papermerge.conf.py is default values + I added an email account

DBUSER = "root"
DBPASS = "root"
DBHOST = "mariadb"
DBNAME = "papermerge"

MEDIA_DIR = "/data/media"
STATIC_DIR = "/app/papermerge/static"
MEDIA_URL = "/media/"
STATIC_URL = "/static/"

IMPORT_MAIL_HOST = "*************"
IMPORT_MAIL_USER = "**********"
IMPORT_MAIL_PASS = "**********"
IMPORT_MAIL_SECRET = "**********"

OCR_DEFAULT_LANGUAGE = "eng"

OCR_LANGUAGES = {
    "eng": "English",
}

**Comment by Goliath67** [comment]
Should I create separate issues?
I am also having trouble with filenames containing accents.
I am in France and if I upload a PDF file such as CalamarsSautés.pdf the file is not loaded (though an emplacement is set for it)
+ Maybe for same reason as the Groups not working, when I create an automate, I can't get a Tag created.

**Comment by tarsnake** [comment]
Same issue (English language).

**Comment by Roxedus** [comment]
Does this still happen? I cannot reproduce
