### ISSUE TITLE
Need to go "into" docker to add other then English language

### ISSUE THREAD

**Issue by tapnl** [linuxserver/docker-papermerge#15]
At this moment the setup is that only English as language is supported out of the box. You can go into docker and install any other language but this is not persistent.

Please add this option.

**Comment by Roxedus** [comment]
We created a mod for this container to allow this. https://github.com/linuxserver/docker-mods/tree/papermerge-multilangocr

**Comment by tapnl** [comment]
Thx, I did not have that clear - got it working!
