### ISSUE TITLE
OCR scan starts, but never completes. (language FRA)

### ISSUE THREAD

**Issue by guim31** [linuxserver/docker-papermerge#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Adding a document should launch an automatic OCR scan.

## Current Behavior
The scan seems to start, but never completes.
https://i.imgur.com/u23vA0u.png

1. I upload a file in any directory
2. The OCR scan starts but never ends

## Environment
Running the latest Docker container on Unraid server.

## Docker logs
https://pastebin.com/83K4rBcc

**Comment by j0nnymoe** [comment]
Please could you provide the docker run command or at least some screenshots of your unraid template?
Thanks

**Comment by guim31** [comment]
Here it is

https://i.imgur.com/JwfmdFg.png

**Comment by j0nnymoe** [comment]
I think it's the gap you have between the `, fra` that is causing the issue.

**Comment by guim31** [comment]
I just correct it, restart the container.... upload the same file again and same result :/

**Comment by j0nnymoe** [comment]
Could you supply the start up logs for the container please?

**Comment by guim31** [comment]
The startup

https://pastebin.com/xcmrGrKf

Here is an interesting line in the docker logs : 

`[2020-11-20 09:59:40,113: ERROR/ForkPoolWorker-2] returncode=1 stdout= stderr=Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/fra.traineddata`

What could be the problem with the fra.trainddata file ?

**Comment by j0nnymoe** [comment]
maybe that's not the correct file name?

**Comment by guim31** [comment]
In fact.... I don't even know where I can find this file / directory...
I ssh my unraid server and pu the file in the usr/share/[..] directory : no effects.
But I'm not sure at all this is the place I should have put it !

**Comment by guim31** [comment]
Anyone to guide me through this ? 🤔

**Comment by csrn** [comment]
Hi @guim31,
 
Did you solve the issue? 

I experienced the same problem with German (the trainneddata file is missing).

How did you transfer the trainneddata file to your server? I curled the file from `https://github.com/tesseract-ocr/tessdata/raw/master/deu.traineddata` but did not notice the github redirection to `https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/deu.traineddata`. It took me a moment to realize the small file size which only contained html. 

Additionally, I had a notification on a missing environment variable (TESSDATA_PREFIX) which I then set to the tessdata directory at `/usr/share/tesseract-ocr/4.00/tessdata/`.

It is working now.

**Comment by guim31** [comment]
Hi @csrn ! I'm still struggling with the issue...
I'll try your steps and let you know.

Thanks A LOT for your message !!

**Comment by guim31** [comment]
So I gave a try at everything, from scratch... and it doesn't work : 

Everything install fine, but I only have ENGLISH language available.
I made sure that the fra.traineddata was in the right directory (it is)

Did I miss something like an env variable ?

**Comment by aptalca** [comment]
Are you guys using the docker mod and setting the right variables?

Post your docker run, because according to an earlier screenshot, @guim31 is not using the correct vars.

See here: https://github.com/linuxserver/docker-mods/tree/papermerge-multilangocr
The correct variable name is `OCRLANG` and not `OCR_LANGUAGES` or `OCR_DEFAULT_LANGUAGE`

**Comment by guim31** [comment]
> Are you guys using the docker mod and setting the right variables?
> 
> Post your docker run, because according to an earlier screenshot, @guim31 is not using the correct vars.
> 
> See here: https://github.com/linuxserver/docker-mods/tree/papermerge-multilangocr
> The correct variable name is `OCRLANG` and not `OCR_LANGUAGES` or `OCR_DEFAULT_LANGUAGE`

You are right, I don't even remember which container / variables I was using at that time.
The fact is I'm now on the right repository, right variables : 

https://i.imgur.com/H5492LO.png

**Comment by aptalca** [comment]
Why are you setting a `TESSDATA_PREFIX`?

**Comment by guim31** [comment]
Because of this comment from @csrn : 
`Additionally, I had a notification on a missing environment variable (TESSDATA_PREFIX) which I then set to the tessdata directory at /usr/share/tesseract-ocr/4.00/tessdata/.`

**Comment by guim31** [comment]
Okay so now I got it working !

I had to edit the `papermerge.conf.py` file within the container, as explained there : https://papermerge.readthedocs.io/en/latest/setup/docker.html

I hope an easy language change within the webUI would be a great add for future updates !!

Thanks a lot everyone for your help and your time.

**Comment by csrn** [comment]
@aptalca: I am not using the mod but the ordinary docker-papermerge repo. Maybe that is the reason @guim31 is still having trouble. Sorry.
