### ISSUE TITLE
/app/papermerge/manage.py does not work - needed for backup and restore operation

### ISSUE THREAD

**Issue by alexkoon** [linuxserver/docker-papermerge#21]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

/app/papermerge/manage.py should work per papermerge documentation at https://papermerge.readthedocs.io/en/latest/backup_restore.html

If you run the command by iteslef if should dump out the standard set of commands avaiable - here is an extract

```
Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[account]
    account_unsetmultipleprimaryemails

[admin]
    logentry

```

## Current Behavior

Output from console is:

`/usr/bin/env: ‘python’: No such file or directory`

## Steps to Reproduce

1. Run a console to the papermerge docker and run /app/papermerge/manage.py
2.
3.
4.

## Environment
**OS:** 
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Fix
I have symlinked in the console /usr/bin/python to /usr/bin/python3

**Comment by Roxedus** [comment]
This is not really a issue with the container. Symlinking python3 to python is not a viable option. In Jan 2021, a whole year after Python2's EOL I would have thought most developers would have updated their shebangs to Python3. `/usr/bin/python3 /app/papermerge/manage.py` works just fine.
