### ISSUE TITLE
Where are my imported documents ?

### ISSUE THREAD

**Issue by nodecentral** [linuxserver/docker-papermerge#25]
I followed the guide to create a Docker instance of paper merge https://docs.linuxserver.io/images/docker-papermerge

------------------------------

**## Expected Behavior**
I was expecting all files I upload to be placed in the local data folder I set up a bind for ?

**## Current Behavior**
The file uploads ok, but I cannot find it anywhere 

**## Steps to Reproduce**
Uploaded a number of files but cant see them 

**## Environment**
**OS:**
**CPU architecture:** x86_64/arm32/arm64
QNAP NAS
**How docker service was installed:**
I just followed the guide

**## Command used to create docker container (run/create/compose/screenshot)**
Here you go.
````
docker run -d \
  --name=papermerge \
  -e PUID=501 \
  -e PGID=100 \
  -e TZ=Europe/London \
  -p 8000:8000 \
  -v /share/Backups/VM/papermerge/config:/config \
  -v /share/Backups/VM/papermerge/data:/data
  ````
The online information - here - https://papermerge.readthedocs.io/en/latest/settings.html#media-dir - suggests (below)

````
MEDIA_DIR

/path/to/media/
context: main app, worker
Defines directory where all uploaded documents will be stored.

By default uses a folder named media in project’s local directory.
````

but where is that ‘media’ directory ?
Nothing is provisioned within the data or config folders used in the Docker creation  ?

**Comment by bdurrer** [comment]
Check the logs, I  had the same issue when I changed the language settings, because the linuxserver container only contains tesseract _english_

**Comment by aptalca** [comment]
@bdurrer we have mods for other langs: https://mods.linuxserver.io/?mod=papermerge
