### ISSUE TITLE
Navigating pages within folders using numbered buttons does not work

### ISSUE THREAD

**Issue by Altomugriento** [linuxserver/docker-papermerge#28]
Description
Pages inside a folder can't be navigated

Expected
Clicking on any number should take you to the corresponding page

Actual
Clicking on any number takes you to the parent folder, click again and lands on the expected folder´s page.

OS: docker
Browser Chrome
Database SQLite
Papermerge Version 2.0rc38

**Comment by ciur** [comment]
Papermerge here.

This bug is not related to docker container. It is application level, so to speak, bug.
It was [reported](https://github.com/ciur/papermerge/issues/324) (and confirmed) on upstream as well.
