### ISSUE TITLE
Testing Release planned for 12th of March 2021

### ISSUE THREAD

**Issue by ciur** [linuxserver/docker-papermerge#31]
Hi guys,

Papermerge here.
For tomorrow (12.03.2021 i.e. 12th of March 2021) I plan test new github action which will be triggered on new tagged release.
This means basically that I will create a series of "test releases".
I saw that you automatically trigger your devops magic when new papermerge release pops-up - and I thought that it may be good idea to inform you that tomorrow will be many "false alarms" :)

I will add relevant comments in tomorrow's " temporary, test releases", but I don't think that your bots will figure that out :)

**Comment by alex-phillips** [comment]
Thanks for the heads up! We'll suspend our build triggers for papermerge until we hear an update from you.

**Comment by ciur** [comment]
Guys, now you can unleash your magic bots :)
I completed my testing part of release management.

Thank you for your fantastic Papermerge docker images, I love their simplity :heart: !

**Comment by aptalca** [comment]
@ciur Thanks so much for the heads up. We re-enabled the triggers and rc48 is now building
