### ISSUE TITLE
A couple of improvement suggestions

### ISSUE THREAD

**Issue by ovizii** [linuxserver/docker-papermerge#38]
Regarding the instructions:

- you could point out what format the REDIS_URL should have, i.e. #redis://papermerge-redis:6379
- you could point out that one still needs to edit these 2 URLs to get papermerge to talk to the correct reddis server:

```
nano config/settings.py
CELERY_BROKER_URL = "redis://papermerge-redis:6379"
CELERY_BROKER_TRANSPORT_OPTIONS = {}
CELERY_RESULT_BACKEND = "redis://papermerge-redis:6379"
```
- your papermerge docker mod makes it sound like all you need to do is to add the mod while you actually need to edit another file to get it setup:

```
nano config/papermerge.conf.py
OCR_DEFAULT_LANGUAGE = "deu"

OCR_LANGUAGES = {
    "eng": "English",
    "deu": "Deutsch",
}
```

**Comment by aptalca** [comment]
As stated in the readme, the `REDIS_URL` env var is only used during first run. We created that var for the image and we specify the format of that env var in the readme. If you don't set it the first time, the readme suggests you can manually edit the settings file later if you wish. We do not manage that file, it is managed by the upstream so you'll have to rely on the upstream docs for that manual step.

We are the maintainers of the docker image but not the upstream app. We have to maintain some sort of separation between the image and the app in terms of support.

We create and support the necessary and often required env vars to get it up and running. We also provide the necessary os dependencies the app needs. But we are not responsible for any further customization you make through the app's GUI or via manually editing the app's config files.

With regards to the docker mod, it installs the os dependency packages for the additional languages. It is not meant to modify the gui settings it the app config to enable a certain language. It also doesn't know which language you want to set as default and allows for installing multiple language packs. You'll have to rely on the app's docs to enable and set as default whichever language you prefer, whether it's through the app's gui or its settings files or env vars.

This is the description of the mod: `This mod adds multi language OCR packages to papermerge and paperless-ng, to be installed/updated during container start.`. To me that's pretty clear but if you have any suggestions on how to make it clearer, feel free to submit a PR.

Thanks
