### ISSUE TITLE
Container not installing languages for OCR likely due to curl error

### ISSUE THREAD

**Issue by Manuel5cc** [linuxserver/docker-papermerge#39]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Additional ocr languages should be installed when the container starts but they don't. This is likely due to a curl/jq error that shows in the logs.
------------------------------

## Expected Behavior

Additional languages should be installed and appear to be selected

## Current Behavior

They don't

## Steps to Reproduce

1. Create a new container including the docker mod for additional language
2.  Run the container
3. Access the UI

## Environment
**OS:** Ubuntu Linux 20.04.3
**CPU architecture:** arm32
**How docker service was installed:**

From the official docker repo

## Command used to create docker container (run/create/compose/screenshot)

Created through Portainer. Screenshots:

![1](https://user-images.githubusercontent.com/21358555/145253390-6ae3a804-3603-4ee8-a96f-f33764f37e34.png)
![vol](https://user-images.githubusercontent.com/21358555/145253404-f7ee9cc8-fe9a-4658-9dfd-2254b14806fc.png)
![cap](https://user-images.githubusercontent.com/21358555/145253405-0d688d07-1bdc-479a-bad0-c6015b119cff.png)
![env](https://user-images.githubusercontent.com/21358555/145253406-67838084-3df7-449a-8fbf-007e95f016eb.png)

## Docker logs

[_papermerge_logs (2).txt](https://github.com/linuxserver/docker-papermerge/files/7677716/_papermerge_logs.2.txt)

**Comment by Roxedus** [comment]
Provide information on how you set up the container, screenshots work.

**Comment by Manuel5cc** [comment]
> Provide information on how you set up the container, screenshots work.

Added

**Comment by aptalca** [comment]
I don't see any curl/jq errors. According to the logs, the language packs are downloaded and installed on the system. Now you can follow whatever directions papermerge provides to enable/select them in the app.

**Comment by Manuel5cc** [comment]
> I don't see any curl/jq errors. According to the logs, the language packs are downloaded and installed on the system. Now you can follow whatever directions papermerge provides to enable/select them in the app.

They seem to be installed but they are not showing in the webui to select

**Comment by Roxedus** [comment]
You need to set up papermerge to look for the languages. https://papermerge.readthedocs.io/en/latest/settings.html#ocr

**Comment by Manuel5cc** [comment]
> You need to set up papermerge to look for the languages. https://papermerge.readthedocs.io/en/latest/settings.html#ocr

Ahhh I see. Maybe a reference for that in the mod's homepage could come in handy for newbies like me.
