### ISSUE TITLE
Missing feature

### ISSUE THREAD

**Issue by brettowe** [linuxserver/docker-papermerge#42]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Trying to access this document page moving: https://docs.papermerge.io/User%27s%20Manual/page_management.html#move-document-to-document

## Current Behavior
the icon is missing to split the window

looking at https://github.com/papermerge/papermerge-core
it says "Page Management - delete, reorder, cut & paste pages (uses [PikePDF](https://github.com/pikepdf/pikepdf))"
checking the docker image I do not see the python library files that are expected

**Comment by Fabiettus** [comment]
Icon to rotate a page is missing too.

**Comment by douglasparker** [comment]
bump

**Comment by ciur** [comment]
I think there is a misunderstanding here regarding 2.0 vs 2.1 versions.

Linuxserver docker image is only for Papermerge DMS 2.0.
While the ticket description reference an issue which exists only in version 2.1.
