### ISSUE TITLE
Move Feature

### ISSUE THREAD

**Issue by Nollknolle** [linuxserver/docker-papermerge#45]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

We need a feature to move files from the inbox to the documents.

## Current Behavior

N/A

**Comment by j0nnymoe** [comment]
You need to report this to the upstream project, not us.
