### ISSUE TITLE
[New Version] 1.4.2

### ISSUE THREAD

**Issue by TynThordin** [linuxserver/docker-papermerge#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
1.4.2 is out: https://github.com/ciur/papermerge/releases/tag/v1.4.2

Please trigger a new build to update to latest (thought you build weekly?)

## Current Behavior
LSIO image only on 1.4.0

## Steps to Reproduce
...

## Environment
...

## Command used to create docker container (run/create/compose/screenshot)
...

## Docker logs
...

**Comment by j0nnymoe** [comment]
This container hasn't been finished for prime time yet. We still need to build the update tracker that follows releases. All will be done in due course :)
