### ISSUE TITLE
Django errors in docker image

### ISSUE THREAD

**Issue by technic88** [linuxserver/docker-papermerge#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Papermerge site should show.

## Current Behavior
Server shows "Internal Server Error" after deployed via Docker. Logs shows errors with django.

## Steps to Reproduce

1. Added via stacks in portainer (see code below)
2. Container starts, shows log output django errors (see attached log)

## Environment
**OS:**      Ubuntu 18.04
**CPU architecture:** x86_64    
**How docker service was installed:**      
Using portainer via stacks.

## Command used to create docker container (run/create/compose/screenshot)
---
version: "2.1"
services:
  papermerge:
    image: linuxserver/papermerge
    container_name: pmerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/Papermerge/Config:/config
      - /mnt/Papermerge/Data:/data

    ports:
      - 8005:8000
    restart: unless-stopped

## Docker logs
[docker-papermerge-log.txt](https://github.com/linuxserver/docker-papermerge/files/5278941/docker-papermerge-log.txt)

**Comment by alex-phillips** [comment]
Can you provide the entire docker log output including the LSIO header?

**Comment by technic88** [comment]
See attached. The last part of the log repeats.
[pmerge_log.txt](https://github.com/linuxserver/docker-papermerge/files/5288836/pmerge_log.txt)

**Comment by HiranChaudhuri** [comment]
I am not the original poster but facing the same symptoms. As far as I could see the error message from the logs looks like

```
[2021-03-07 22:01:59,480: ERROR/ForkPoolWorker-2] Task papermerge.core.management.commands.worker.txt2db[1ed1b908-14d8-4a6f-abbc-63712b10b057] raised unexpected: OperationalError('no such table: core_document')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_document
```

At the same time I can see that in the data directory that I mounted an empty file `papermerge.db` was created.

So all in all I assume the error is caused because the database is not initialized. This is documented in the detailed installation version step 3 on https://www.papermerge.com/docs/Installation/installation.html:
_run migrations - in django’s jargon means that you prepare the database. By default Papermerge (as any Django based project) uses sqlite database - which is stored in a single file. ./manage.py migrate command will create that file (it is called db.sqlite3 and is in project’s root directory) and create database schema for the project._

**Comment by HiranChaudhuri** [comment]
Seems not that easy to circumvent. I just ran
```
$ docker exec -it papermerge bash
# ln -s /usr/bin/python3 /usr/bin/python
# cd /app/papermerge
# ./manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, core, dynamic_preferences, dynamic_preferences_users, knox, sessions, sites, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked
```

**Comment by HiranChaudhuri** [comment]
So I just learned about cont-init.d, from which the migrate step is actually called. Also here I see an error:
```
[cont-init.d] 50-config: executing... 
No changes detected
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, core, dynamic_preferences, dynamic_preferences_users, knox, sessions, sites, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked
```

**Comment by HiranChaudhuri** [comment]
So at least in my case the issue is connected with the volume I mounted on /data. As soon as I removed that, the papermerge container was able to startup correctly. It is a CIFS volume mount so I will have to check privileges carefully. Sorry for bothering...

**Comment by tobbenb** [comment]
Sqlite on cifs mounts bindmounted in the container usually doesn't work as sqlite doesn't like fuse file systems.

**Comment by HiranChaudhuri** [comment]
Thank you for that hint. So I'd have to separate the database from the documents. On the other hand... I want the important data to reside on my NAS. Would an NFS mount work?
